version: '3'
services:
  redispublisher:
    build:
      context: .
      dockerfile: apps/e2e-redis-publisher-sample/Dockerfile
    links:
      - msg
    environment:
      REDIS_URL: redis://msg:6379
  redissubscriber:
    build:
      context: .
      dockerfile: apps/e2e-redis-subscriber-sample/Dockerfile
    links:
      - db
      - msg
    environment:
      MONGO_URL: mongodb://db:27017/logs
      REDIS_URL: redis://msg:6379
  redise2etest:
    build:
      context: .
      dockerfile: e2e-testing/Dockerfile
    command:
      ['npm', 'test e2e-testing/e2e-redis.spec.ts -- --config jest.e2e.js']
    depends_on:
      - redispublisher
      - redissubscriber
    environment:
      PUBLISHER_URL: http://redispublisher:3000
      SUBSCRIBER_URL: http://redissubscriber:4000
  db:
    image: mongo:3
  msg:
    image: redis:4.0-alpine
